session_0/kavyabhat
IRIS-NITK/IRIS-RoR-Bootcamp-2020 pull request #31
Opened 2021-01-05 16:02 UTC by kavyabhat02

Please review my code for fizz_buzz and item.

2021-01-06 16:28 UTC, abhishekkumar2718 requested changes

2021-01-06 16:28 UTC, abhishekkumar2718 commented on session_0/fizz_buzz.rb
> +   array.map{ |k|
We prefer the `do-end` syntax for a mult-line block:

```ruby
array.map do |k|
  ...
end
```

https://rubystyle.guide/#single-line-blocks

2021-01-06 16:28 UTC, abhishekkumar2718 commented on session_0/fizz_buzz.rb
> +   if(n<0)||(x<=0)||(y<=0)
https://rubystyle.guide/#spaces-operators

2021-01-06 16:28 UTC, abhishekkumar2718 commented on session_0/item.rb
> +    if(Time.now>@discount_deadline)
What happens when `Time.now` is equal to `@discount_deadline`? Is the item discounted or not?

2021-01-06 16:28 UTC, abhishekkumar2718 commented on session_0/item.rb
> +      return @price*(100-@discount_rate)/100
Since we have defined `attr_accessor` for the variables - you can use `price` instead of specifying `@price`

2021-01-06 16:28 UTC, abhishekkumar2718 commented on session_0/item.rb
> +     final = {
What if there were 100 categories? Could you still write them out by hand?

2021-01-06 16:28 UTC, abhishekkumar2718 commented
Feel free to ask @addhyanmalhotra if you need hints for the word processing problem

2021-01-07 01:06 UTC, kavyabhat02 commented
Thanks, but I haven't gotten around to solving the word_processing problem yet, I'm still working on session_0. 
Also, thanks for the suggestions, I'll implement them in the code.

2021-01-09 11:03 UTC, abhishekkumar2718 commented
Closed due to a more recent PR: #42

2021-01-09 11:04 UTC, closed without merging